DELETE FROM metaifn.abmode WHERE unite = 'AGENCES_ONF';
DELETE FROM metaifn.abunite WHERE unite = 'AGENCES_ONF';

INSERT INTO metaifn.abunite(unite, proprietaire, utype, libelle, definition) VALUES ('AGENCES_ONF', 'IFN', 'NOMINAL', 'Agences ONF 2023', 'Agences ONF 2023');

INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8320','Agence territoriale PAYS DE LA LOIRE','Agence territoriale PAYS DE LA LOIRE', 0);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8325','Agence territoriale BRETAGNE','Agence territoriale BRETAGNE', 1);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8330','Agence territoriale POITOU-CHARENTES','Agence territoriale POITOU-CHARENTES', 2);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8335','Agence territoriale VAL DE LOIRE','Agence territoriale VAL DE LOIRE', 3);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8345','Agence territoriale LIMOUSIN','Agence territoriale LIMOUSIN', 4);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8355','Agence territoriale BERRY - BOURBONNAIS','Agence territoriale BERRY - BOURBONNAIS', 5);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8365','Agence territoriale LANDES - NORD AQUITAINE','Agence territoriale LANDES - NORD AQUITAINE', 6);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8370','Agence territoriale PYRÉNÉES-ATLANTIQUES','Agence territoriale PYRÉNÉES-ATLANTIQUES', 7);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8415','Agence territoriale DU JURA','Agence territoriale DU JURA', 8);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8420','Agence territoriale DE VESOUL','Agence territoriale DE VESOUL', 9);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8425','Agence territoriale NORD FRANCHE-COMTÉ','Agence territoriale NORD FRANCHE-COMTÉ', 10);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8440','Agence territoriale DE BESANCON','Agence territoriale DE BESANCON', 11);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8450','Agence territoriale BOURGOGNE-OUEST','Agence territoriale BOURGOGNE-OUEST', 12);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8455','Agence territoriale BOURGOGNE-EST','Agence territoriale BOURGOGNE-EST', 13);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8505','Agence territoriale NORD ET PAS-DE-CALAIS','Agence territoriale NORD ET PAS-DE-CALAIS', 14);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8510','Agence territoriale PICARDIE','Agence territoriale PICARDIE', 15);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8515','Agence territoriale ILE-DE-FRANCE EST','Agence territoriale ILE-DE-FRANCE EST', 16);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8520','Agence territoriale ILE-DE-FRANCE OUEST','Agence territoriale ILE-DE-FRANCE OUEST', 17);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8530','Agence territoriale D'ALENÇON','Agence territoriale D'ALENÇON', 18);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8535','Agence territoriale DE ROUEN','Agence territoriale DE ROUEN', 19);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8615','Agence territoriale DE BAR-LE-DUC','Agence territoriale DE BAR-LE-DUC', 20);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8620','Agence territoriale DE VERDUN','Agence territoriale DE VERDUN', 21);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8625','Agence territoriale DE METZ','Agence territoriale DE METZ', 22);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8630','Agence territoriale DE SARREBOURG','Agence territoriale DE SARREBOURG', 23);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8660','Agence territoriale VOSGES-OUEST','Agence territoriale VOSGES-OUEST', 24);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8665','Agence territoriale MEURTHE-ET-MOSELLE','Agence territoriale MEURTHE-ET-MOSELLE', 25);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8670','Agence territoriale VOSGES-MONTAGNE','Agence territoriale VOSGES-MONTAGNE', 26);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8681','Agence territoriale DES ARDENNES','Agence territoriale DES ARDENNES', 27);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8682','Agence territoriale AUBE - MARNE','Agence territoriale AUBE - MARNE', 28);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8683','Agence territoriale DE HAUTE-MARNE','Agence territoriale DE HAUTE-MARNE', 29);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8691','Agence territoriale NORD ALSACE','Agence territoriale NORD ALSACE', 30);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8692','Agence territoriale DE SCHIRMECK','Agence territoriale DE SCHIRMECK', 31);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8693','Agence territoriale DU HAUT-RHIN','Agence territoriale DU HAUT-RHIN', 32);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8720','Agence territoriale LOZÈRE','Agence territoriale LOZÈRE', 33);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8730','Agence territoriale ALPES-DE-HAUTE-PROVENCE','Agence territoriale ALPES-DE-HAUTE-PROVENCE', 34);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8735','Agence territoriale HAUTES-ALPES','Agence territoriale HAUTES-ALPES', 35);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8745','Agence territoriale BOUCHES-DU-RHÔNE - VAUCLUSE','Agence territoriale BOUCHES-DU-RHÔNE - VAUCLUSE', 36);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8760','Agence territoriale ARIEGE AUDE PYRENEES ORIENTALES','Agence territoriale ARIEGE AUDE PYRENEES ORIENTALES', 37);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8765','Agence territoriale HÉRAULT - GARD','Agence territoriale HÉRAULT - GARD', 38);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8770','Agence territoriale ALPES-MARITIMES - VAR','Agence territoriale ALPES-MARITIMES - VAR', 39);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8775','Agence territoriale AVEYRON - LOT - TARN - TARN-ET-GARONNE','Agence territoriale AVEYRON - LOT - TARN - TARN-ET-GARONNE', 40);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8790','Agence territoriale PYRENEES - GASCOGNE','Agence territoriale PYRENEES - GASCOGNE', 41);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8805','Agence territoriale AIN - LOIRE - RHÔNE','Agence territoriale AIN - LOIRE - RHÔNE', 42);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8810','Agence territoriale DRÔME - ARDÈCHE','Agence territoriale DRÔME - ARDÈCHE', 43);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8815','Agence territoriale ISÈRE','Agence territoriale ISÈRE', 44);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8835','Agence territoriale MONTAGNES D'AUVERGNE','Agence territoriale MONTAGNES D'AUVERGNE', 45);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '8845','Agence territoriale SAVOIE MONT BLANC','Agence territoriale SAVOIE MONT BLANC', 46);
INSERT INTO metaifn.abmode(unite, mode, libelle, definition, position) VALUES ('AGENCES_ONF', '9005','Agence territoriale DE CORSE','Agence territoriale DE CORSE', 47);

